int $size = 5;
polySphere -r $size -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;
$size = $size - 1;
polySphere -r $size -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;
move -r 0 7 0;
$size = $size - 1;
polySphere -r $size -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;
move -r 0 12 0;

//button1
$size = $size - 2.25;
polySphere -r $size -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;
move -r 0 2.75 4;
//button2
duplicate -rr;
move -r 0 3.25 -0.25;
//button3
duplicate -rr;
move -r 0 2.75 -0.25;

//face
//eye1
duplicate -rr;
move -r 1.5 3.5 -1.25;
//eye2
duplicate -rr;
move -r -3 0 0;

//nose
polyCone -r 0.5 -h 2.5 -sx 20 -sy 1 -sz 5 -ax 0 1 0 -rcp 0 -cuv 3 -ch 1;
move -r 0 12 4;
rotate -r -os -fo 90 0;
